version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@3.2

commands:
  build-image: aws-ecr/build-image

workflows:
  deploy-to-development:
    jobs:
      - aws-ecr/build-and-push-image:
          name: "build-and-push-image"
          context:
            - KAIRAT_CONTEXT
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ACCOUNT_ECR_URL
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: $AWS_ACCOUNT_ECR_NAME
          skip-when-tags-exist: false
          tag: dev-$CIRCLE_SHA1
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          context:
            - KAIRAT_CONTEXT
          cluster: test-cluster
          container-image-name-updates: 'container=test-container2,tag=dev-${CIRCLE_SHA1}'
          family: test-task2
          service-name: test-service
          force-new-deployment: true
          filters:
            branches:
              only:
                - main
          requires:
